### ISSUE TITLE
fail executing flask run, cause configuration api docs on TEAL missing arguments

### ISSUE THREAD

**Issue by jnadeu** [eReuse/tag#1]
To recreate this issue, using app.py inside example folder without using apache or wsgi:
I execute `flask run`

Then appears this error:

_File "/home/nad/Work/Ereuse/Github/t.devicetag.io/tag/app.py", line 25, in <module>
    app = Teal(config=DeviceTagConf(), db=db, Auth=Auth)
  File "/home/nad/Work/Ereuse/Github/t.devicetag.io/venv/lib/python3.7/site-packages/teal/teal.py", line 108, in __init__
    self.apidocs()
  File "/home/nad/Work/Ereuse/Github/t.devicetag.io/venv/lib/python3.7/site-packages/teal/teal.py", line 244, in apidocs
    **self.config.get_namespace('API_DOC_CONFIG_')
TypeError: __init__() missing 1 required positional argument: 'openapi_version'_

I SOLVED temporally commenting inside `[Teal](https://github.com/eReuse/teal)` packages, in teal.py file, line 108 self.apidocs() and then `flask run` works fine and server starts.

I tried to add API_DOC_CONFIG like [Devicehub example](https://github.com/eReuse/devicehub-teal/blob/master/ereuse_devicehub/config.py) but error persist..

**Comment by slamora** [comment]
Fixed on #2
